services:
  - type: web
    name: chat-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://nikhil:nikhildath2008@cluster0.9qqyjlc.mongodb.net/
